# fzf
set -U FZF_LEGACY_KEYBINDINGS 0

balias g 'git'
balias gb 'git branch'
balias gco 'git checkout'
balias gcm 'git checkout master'
balias gs 'git status'
balias ga 'git add'
balias gd 'git diff'
balias gr 'git remote'
balias gc 'git commit'
balias gp 'git push'
balias gm 'git merge'
balias gl 'git pull'
balias gf 'git fetch'
balias gfa 'git fetch --all --prune'
balias glg 'git log --stat'
balias l 'ls -lah'
balias ll 'ls -lh'
balias 1 'cd -'
balias 2 'cd -2'
